name: "Install & cache dependencies"

runs:
  using: "composite"

  steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: node_modules
        # Generate a new cache whenever packages or source files change.
        key: ${{ runner.os }}-nest-js-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        # If source files changed but packages didn't, rebuild from a prior cache.
        restore-keys: |
          ${{ runner.os }}-nest-js-${{ hashFiles('**/pnpm-lock.yaml') }}-
          ${{ runner.os }}-nest-js-

    - name: Install dependencies
      shell: bash
      run: pnpm install
