name: Check Nest.js project

on: pull_request

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}

  POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
  POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
  POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
  GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}

  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
  ACCESS_TOKEN_VALIDITY: ${{ secrets.ACCESS_TOKEN_VALIDITY }}
  REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
  REFRESH_TOKEN_VALIDITY: ${{ secrets.REFRESH_TOKEN_VALIDITY }}

  AUTH_REDIRECT_URL: ${{ secrets.AUTH_REDIRECT_URL }}
  CORS_ORIGINS: ${{ secrets.CORS_ORIGINS }}

jobs:
  check:
    name: Check project
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/actions/install-dependencies

      - name: Check Typescript errors
        run: pnpm run ts:check

      - name: Check ESLint errors
        run: pnpm run lint:check

      - name: Check Prettier errors
        run: pnpm run format:check

  tests:
    name: Run unit & e2e tests
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:16.2
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: $POSTGRES_USER
          POSTGRES_PASSWORD: $POSTGRES_PASSWORD
          POSTGRES_DB: $POSTGRES_DB

    steps:
      - uses: ./.github/actions/install-dependencies

      - name: Generate prisma client
        run: pnpm prisma:gen

      - name: Seed database
        run: pnpm prisma:seed

      - name: Run unit tests
        run: pnpm run test

      - name: Run e2e tests
        run: pnpm run test:e2e
